name: "Run tests"
description: "Run tests"

inputs:
  anki:
    description: "Anki version"
    required: true
  python:
    description: "Python interpreter version"
    required: true
  pyqt:
    description: "PyQt widget toolkit version"
    required: true
  pyqtwebengine:
    description: "PyQt WebEngine version"
    required: true
  chrome:
    description: "Chrome version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout pytest-anki
      uses: actions/checkout@v2

    - name: "Set up environment"
      uses: ./.github/actions/setup_env
      with:
        anki: ${{ inputs.anki }}
        python: ${{ inputs.python }}
        pyqt: ${{ inputs.pyqt }}
        pyqtwebengine: ${{ inputs.pyqtwebengine }}
        chrome: ${{ inputs.chrome }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.8
        virtualenvs-create: false

    - name: Set up pytest-anki
      shell: bash
      run: |
        make install

    - name: Run tests for Anki ${{ matrix.anki }}
      shell: bash
      run: |
        make test
