name: "Run tests"
description: "Run tests"

inputs:
  anki_version:
    description: "Anki version"
    required: true
  python_version:
    description: "Python interpreter version"
    required: true
  pyqt_version:
    description: "PyQt widget toolkit version"
    required: true
  pyqtwebengine_version:
    description: "PyQt WebEngine version"
    required: true
  chrome_version:
    description: "Chrome version"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Set up environment"
      uses: ./.github/actions/setup_env
      with:
        anki_version: ${{ matrix.anki }}
        python_version: ${{ matrix.python }}
        pyqt_version: ${{ matrix.pyqt }}
        pyqtwebengine_version: ${{ matrix.pyqtwebengine }}
        chrome_version: ${{ matrix.chrome }}

    - name: Checkout pytest-anki
      uses: actions/checkout@v2

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.1.8
        virtualenvs-create: false

    - name: Set up pytest-anki
      shell: bash
      run: |
        make install

    - name: Run tests for Anki ${{ matrix.anki }}
      shell: bash
      run: |
        make test
