name: "Set up Anki"
description: "Set up Anki"

inputs:
  anki:
    description: "Anki version. If set to 'latest', this will install latest (pre)-release."
    required: true
  pyqt:
    description: "PyQt widget toolkit version"
    required: true
  pyqtwebengine:
    description: "PyQt WebEngine version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Anki ${{ inputs.anki }}
      shell: bash
      run: |
        pip install --upgrade setuptools pip
        pip install --upgrade PyQt5==${{ inputs.pyqt }} PyQtWebEngine==${{ inputs.pyqtwebengine }}

        if [[ "${{ inputs.anki }}" == "latest" ]]; then
          pip install --upgrade --pre anki aqt
        else:
          pip install --upgrade anki==${{ inputs.anki }} aqt==${{ inputs.anki }}
        fi
