name: "Set up Anki"
description: "Set up Anki"

inputs:
  # The defaults are based on the latest tested Anki release. Updates to them usually
  # only occur every few Anki releases, typically with months between them.
  # As a result, this should be a reasonable enough strategy to allow us to test
  # new Anki pre-releases without knowing the exact dependency set-up.
  anki:
    description: "Anki version. Set this to 'prerelease' to install either the latest release or prerelease."
    required: false
    default: 2.1.47
  pyqt:
    description: "PyQt widget toolkit version"
    required: false
    default: 5.14.2
  pyqtwebengine:
    description: "PyQt WebEngine version"
    required: false
    default: 5.14.0

runs:
  using: "composite"
  steps:
    - name: Set up Anki ${{ inputs.anki }}
      shell: bash
      run: |
        pip install --upgrade setuptools pip
        pip install --upgrade PyQt5==${{ inputs.pyqt }} PyQtWebEngine==${{ inputs.pyqtwebengine }}

        if [[ "${{ inputs.anki }}" == "prerelease" ]]; then
          pip install --upgrade --pre anki aqt
        else:
          pip install --upgrade anki==${{ inputs.anki }} aqt==${{ inputs.anki }}
        fi
