name: tests

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
  push:
    branches:
      - main

jobs:
  pytest-current:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout pytest-anki
        uses: actions/checkout@v2
      - name: Run tests
        uses: ./.github/actions/run_tests
        # uses default values which are specified in setup_ actions for the latest
        # tested Anki release

  pytest-legacy:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          # Version matrix follows static macOS builds as closely as possible.
          # Some Qt package versions are not available on PyPI, so we need to make
          # compromises here and there.
          - anki: 2.1.44
            python: 3.8.6
            pyqt: 5.14.2
            pyqtwebengine: 5.14.0
            chrome: 77.0.3865.129
          - anki: 2.1.35
            python: 3.8.0
            pyqt: 5.14.2
            pyqtwebengine: 5.14.0
            chrome: 77.0.3865.129
          - anki: 2.1.28
            python: 3.8.0
            pyqt: 5.15.0
            pyqtwebengine: 5.15.0
            chrome: 80.0.3987.163
          - anki: 2.1.26
            python: 3.8.0
            pyqt: 5.13.1
            pyqtwebengine: 5.13.1
            chrome: 73.0.3683.105

    steps:
      - name: Checkout pytest-anki
        uses: actions/checkout@v2
      - name: Run tests
        uses: ./.github/actions/run_tests
        with:
          anki: ${{ matrix.anki }}
          python: ${{ matrix.python }}
          pyqt: ${{ matrix.pyqt }}
          pyqtwebengine: ${{ matrix.pyqtwebengine }}
          chrome: ${{ matrix.chrome }}

  lint-and-check:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout pytest-anki
        uses: actions/checkout@v2

      - name: Run checks
        uses: ./.github/actions/run_checks
        # uses default values which are specified in setup_ actions for the latest
        # tested Anki release
