name: tests

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
            - anki: 2.1.46
              python: 3.8.6
              pyqt: 5.15.1
              pyqtwebengine: 5.15.1
            - anki: 2.1.44
              python: 3.8.6
              pyqt: 5.14.2
              pyqtwebengine: 5.14.0
            - anki: 2.1.35
              python: 3.8.0
              pyqt: 5.14.2
              pyqtwebengine: 5.14.0
            - anki: 2.1.28
              python: 3.8.0
              pyqt: 5.15.0
              pyqtwebengine: 5.15.0

    steps:
      # Qt5 requires a number of X11-related dependencies to be installed system-wide
      # Rather than installing each individually, we install libqt5 system-wide which
      # in turn takes care of installing all deps also needed for the pypi-version of
      # Qt5
      - name: Install xvfb / qt dependencies
        run: |
          sudo apt-get install libqt5gui5

      - name: Checkout pytest-anki
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.8
          virtualenvs-create: false

      - name: Set up pytest-anki
        run: |
          make install

      - name: Set up Anki ${{ matrix.anki }}
        run: |
          pip install --upgrade setuptools pip
          pip install --upgrade PyQt5==${{ matrix.pyqt }} PyQtWebEngine==${{ matrix.pyqtwebengine }} anki==${{ matrix.anki }} aqt==${{ matrix.anki }}

      - name: Run tests for Anki ${{ matrix.anki }}
        run: |
          make test
