name: pytest-anki tests

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install xvfb dependencies
        run: |
          sudo apt-get install xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-render-util0 libxcb-image0 libxcb-keysyms1

      - name: Checkout pytest-anki
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.8
          virtualenvs-create: false

      - name: Run tests
        run: |
          ./tools/run_tests.sh
