name: tests

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          # Version matrix follows static macOS builds as closely as possible.
          # Some Qt package versions are not available on PyPI, so we need to make
          # compromises here and there.
          - anki: 2.1.47
            python: 3.8.6
            pyqt: 5.14.2
            pyqtwebengine: 5.14.0
            chrome: 77.0.3865.129
          - anki: 2.1.44
            python: 3.8.6
            pyqt: 5.14.2
            pyqtwebengine: 5.14.0
            chrome: 77.0.3865.129
          - anki: 2.1.35
            python: 3.8.0
            pyqt: 5.14.2
            pyqtwebengine: 5.14.0
            chrome: 77.0.3865.129
          - anki: 2.1.28
            python: 3.8.0
            pyqt: 5.15.0
            pyqtwebengine: 5.15.0
            chrome: 80.0.3987.163
          - anki: 2.1.26
            python: 3.8.0
            pyqt: 5.13.1
            pyqtwebengine: 5.13.1
            chrome: 73.0.3683.105

    steps:
      - uses: ./.github/actions/run_tests
        with:
          anki_version: ${{ matrix.anki }}
          python_version: ${{ matrix.python }}
          pyqt_version: ${{ matrix.pyqt }}
          pyqtwebengine_version: ${{ matrix.pyqtwebengine }}
          chrome_version: ${{ matrix.chrome }}

  lint-and-check:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - anki: 2.1.47
            python: 3.8.6
            pyqt: 5.14.2
            pyqtwebengine: 5.14.0
    steps:
      - name: Checkout pytest-anki
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.8
          virtualenvs-create: false

      - name: Set up pytest-anki
        run: |
          make install

      - name: Set up Anki ${{ matrix.anki }}
        run: |
          pip install --upgrade setuptools pip
          pip install --upgrade PyQt5==${{ matrix.pyqt }} PyQtWebEngine==${{ matrix.pyqtwebengine }} anki==${{ matrix.anki }} aqt==${{ matrix.anki }}

      - name: Run type checker for Anki ${{ matrix.anki }}
        run: |
          make check

      - name: Run linter for Anki ${{ matrix.anki }}
        run: |
          make lint
