name: tests

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - "README.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout pytest-anki
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Install anki
        run: |
          python -m pip install --upgrade pip
          pip install aqt
          pip install .

      - name: Run tests
        run: |
          ./tools/run_tests.sh
