name: tests

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
  push:
    branches:
      - main

jobs:
  check-and-test-current-anki:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        include:
          # Configuration based on latest tested macOS static build for Anki
          # Updates to the dependencies specified here usually only occur every
          # few Anki releases.
          - anki: 2.1.47
            python: 3.8.6
            pyqt: 5.14.2
            pyqtwebengine: 5.14.0
            chrome: 77.0.3865.129

    steps:
      - name: Checkout pytest-anki
        uses: actions/checkout@v2
      
      - name: Set up test environment
        uses: ./.github/actions/setup
        with:
          python: ${{ matrix.python }}
          chrome: ${{ matrix.chrome }}
          anki: ${{ matrix.anki }}
          pyqt: ${{ matrix.pyqt }}
          pyqtwebengine: ${{ matrix.pyqtwebengine }}
      
      - name: Run type checker for Anki ${{ matrix.anki }}
        shell: bash
        run: |
          make check

      - name: Run linter for Anki ${{ matrix.anki }}
        shell: bash
        run: |
          make lint
      
      - name: Run tests for Anki ${{ matrix.anki }}
        shell: bash
        run: |
          make test

  test-old-anki:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          # Version matrix follows static macOS builds as closely as possible.
          # Some Qt package versions are not available on PyPI, so we need to make
          # compromises here and there.
          - anki: 2.1.44
            python: 3.8.6
            pyqt: 5.14.2
            pyqtwebengine: 5.14.0
            chrome: 77.0.3865.129
          - anki: 2.1.35
            python: 3.8.0
            pyqt: 5.14.2
            pyqtwebengine: 5.14.0
            chrome: 77.0.3865.129
          - anki: 2.1.28
            python: 3.8.0
            pyqt: 5.15.0
            pyqtwebengine: 5.15.0
            chrome: 80.0.3987.163
          - anki: 2.1.26
            python: 3.8.0
            pyqt: 5.13.1
            pyqtwebengine: 5.13.1
            chrome: 73.0.3683.105

    steps:
      - name: Checkout pytest-anki
        uses: actions/checkout@v2

      - name: Set up test environment
        uses: ./.github/actions/setup
        with:
          python: ${{ matrix.python }}
          chrome: ${{ matrix.chrome }}
          anki: ${{ matrix.anki }}
          pyqt: ${{ matrix.pyqt }}
          pyqtwebengine: ${{ matrix.pyqtwebengine }}

      - name: Run tests for Anki ${{ matrix.anki }}
        shell: bash
        run: |
          make test
