name: tests

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      # Qt5 requires a number of X11-related dependencies to be installed system-wide
      # Rather than installing each individually, we install libqt5 system-wide which
      # in turn takes care of installing all deps also needed for the pypi-version of
      # Qt5
      - name: Install xvfb / qt dependencies
        run: |
          sudo apt-get install libqt5gui5

      - name: Checkout pytest-anki
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.8
          virtualenvs-create: false

      - name: Run tests
        run: |
          ./tools/run_tests.sh
